phpstan:
  image: harbor.ulbricht.casa/jinya/jinya-cms-php-base-test-image:latest
  stage: test
  script:
    - ./vendor/bin/phpstan --no-progress analyze ./src ./tests
 
phpunit:
  image: harbor.ulbricht.casa/jinya/jinya-cms-php-base-test-image:latest
  stage: test
  script:
    - ./vendor/bin/phpunit --log-junit report.xml --configuration ./phpunit.xml --coverage-text --coverage-cobertura=build/coverage.cobertura.xml
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit:
        - report.xml
      coverage_report:
        coverage_format: cobertura
        path: build/coverage.cobertura.xml

pages:
  image: harbor.ulbricht.casa/proxy/library/node:latest
  stage: deploy
  script:
    - cd docs
    - npm install
    - npm run build
    - mv ./build ../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
